import {
  ArrowLeft,
  ArrowRight,
  Calendar,
  Check,
  ChevronDown,
  CircleCheck,
  Download,
  FileText,
  Folder,
  Info,
  Plus,
  Receipt,
  Search,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  X,
} from "lucide-solid"

export const Icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  calendar: Calendar,
  check: Check,
  checkCircle: CircleCheck,
  close: X,
  folder: Folder,
  info: Info,
  users: Users,
  user: User,
  fileText: FileText,
  plus: Plus,
  receipt: Receipt,
  search: Search,
  trendingUp: TrendingUp,
  upload: Upload,
  download: Download,
  trash: Trash2,
} as const
