import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart3,
  Bell,
  Calendar,
  ChevronDown,
  Clock,
  Download,
  Edit,
  FileText,
  Folder,
  GraduationCap,
  Home,
  Lock,
  LogOut,
  Menu,
  Plus,
  Search,
  Settings,
  Trash2,
  Upload,
  User,
  Users,
  X,
} from "lucide-solid"

export const Icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  calendar: Calendar,
  clock: Clock,
  folder: Folder,
  users: Users,
  fileText: FileText,
  plus: Plus,
  search: Search,
  upload: Upload,
  download: Download,
  trash: Trash2,
  logout: LogOut,
  user: User,
  bell: Bell,
  menu: Menu,
  lock: Lock,
  alert: AlertTriangle,
  settings: Settings,
  graduationCap: GraduationCap,
  home: Home,
  barChart3: BarChart3,
  close: X,
  edit: Edit,
} as const
