import {
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  BarChart3,
  Bell,
  Box,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  Edit,
  Eye,
  EyeOff,
  FileText,
  Folder,
  GraduationCap,
  Home,
  Info,
  Landmark,
  Lock,
  LogOut,
  Mail,
  Menu,
  Minus,
  Moon,
  Package,
  PanelLeftClose,
  PanelLeftOpen,
  Plus,
  Receipt,
  Search,
  Settings,
  ShoppingBag,
  Sun,
  Sunrise,
  Trash2,
  Upload,
  User,
  Users,
  Wallet,
  X,
  XCircle,
} from "lucide-solid"

export const Icons = {
  alert: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowLeftRight: ArrowLeftRight,
  arrowRight: ArrowRight,
  barChart3: BarChart3,
  bell: Bell,
  box: Box,
  calendar: Calendar,
  check: Check,
  checkCircle: CheckCircle,
  chevronDown: ChevronDown,
  clock: Clock,
  close: X,
  creditCard: CreditCard,
  download: Download,
  edit: Edit,
  eye: Eye,
  eyeOff: EyeOff,
  fileText: FileText,
  folder: Folder,
  graduationCap: GraduationCap,
  home: Home,
  info: Info,
  landmark: Landmark,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  minus: Minus,
  moon: Moon,
  package: Package,
  panelLeftClose: PanelLeftClose,
  panelLeftOpen: PanelLeftOpen,
  plus: Plus,
  receipt: Receipt,
  search: Search,
  settings: Settings,
  shoppingBag: ShoppingBag,
  sun: Sun,
  sunrise: Sunrise,
  trash: Trash2,
  upload: Upload,
  user: User,
  users: Users,
  wallet: Wallet,
  xCircle: XCircle,
} as const

/** Mapping of portal IDs to their canonical icon (used in main-portal card grid) */
export const PortalIcons = {
  batches: Folder,
  students: Users,
  training: GraduationCap,
  procurement: ShoppingBag,
  inventory: Package,
  finance: DollarSign,
  billing: Receipt,
  hr: Users,
} as const
