import {
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  BarChart3,
  Bell,
  Box,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  Clock,
  CreditCard,
  Download,
  Edit,
  FileText,
  Folder,
  GraduationCap,
  Home,
  Info,
  Landmark,
  Lock,
  LogOut,
  Menu,
  Minus,
  Package,
  Plus,
  Receipt,
  Search,
  Settings,
  ShoppingBag,
  Trash2,
  Upload,
  User,
  Users,
  Wallet,
  X,
  XCircle,
} from "lucide-solid"

export const Icons = {
  alert: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowLeftRight: ArrowLeftRight,
  arrowRight: ArrowRight,
  barChart3: BarChart3,
  bell: Bell,
  box: Box,
  calendar: Calendar,
  check: Check,
  checkCircle: CheckCircle,
  chevronDown: ChevronDown,
  clock: Clock,
  close: X,
  creditCard: CreditCard,
  download: Download,
  edit: Edit,
  fileText: FileText,
  folder: Folder,
  graduationCap: GraduationCap,
  home: Home,
  info: Info,
  landmark: Landmark,
  lock: Lock,
  logout: LogOut,
  menu: Menu,
  minus: Minus,
  package: Package,
  plus: Plus,
  receipt: Receipt,
  search: Search,
  settings: Settings,
  shoppingBag: ShoppingBag,
  trash: Trash2,
  upload: Upload,
  user: User,
  users: Users,
  wallet: Wallet,
  xCircle: XCircle,
} as const
