import {
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Calendar,
  ChevronDown,
  Download,
  FileText,
  Folder,
  Info,
  Landmark,
  Plus,
  Receipt,
  Search,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  Wallet,
  X,
} from "lucide-solid"

export const Icons = {
  arrowLeft: ArrowLeft,
  arrowLeftRight: ArrowLeftRight,
  arrowRight: ArrowRight,
  arrowDown: ArrowDown,
  chevronDown: ChevronDown,
  calendar: Calendar,
  close: X,
  folder: Folder,
  info: Info,
  landmark: Landmark,
  users: Users,
  user: User,
  fileText: FileText,
  plus: Plus,
  receipt: Receipt,
  search: Search,
  trendingUp: TrendingUp,
  upload: Upload,
  download: Download,
  trash: Trash2,
  wallet: Wallet,
} as const
