import {
  ArrowLeft,
  ArrowRight,
  Briefcase,
  Calendar,
  CheckCircle,
  ChevronDown,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  FileText,
  Folder,
  Hash,
  Info,
  LogIn,
  LogOut,
  Plus,
  Search,
  Trash2,
  Upload,
  User,
  UserCheck,
  Users,
  X,
  XCircle,
} from "lucide-solid"

export const Icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  briefcase: Briefcase,
  calendar: Calendar,
  checkCircle: CheckCircle,
  chevronDown: ChevronDown,
  clock: Clock,
  close: X,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  download: Download,
  fileText: FileText,
  folder: Folder,
  hash: Hash,
  info: Info,
  logIn: LogIn,
  logout: LogOut,
  plus: Plus,
  search: Search,
  trash: Trash2,
  upload: Upload,
  user: User,
  userCheck: UserCheck,
  users: Users,
  xCircle: XCircle,
} as const
