import {
  ArrowLeft,
  ArrowRight,
  Calendar,
  CheckCircle,
  ChevronDown,
  Download,
  FileText,
  Folder,
  Info,
  LogOut,
  Plus,
  Search,
  ShoppingBag,
  ShoppingCart,
  Trash2,
  Upload,
  User,
  Users,
  X,
  XCircle,
} from "lucide-solid"

export const Icons = {
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronDown: ChevronDown,
  calendar: Calendar,
  close: X,
  folder: Folder,
  users: Users,
  fileText: FileText,
  plus: Plus,
  search: Search,
  upload: Upload,
  download: Download,
  trash: Trash2,
  shoppingCart: ShoppingCart,
  shoppingBag: ShoppingBag,
  checkCircle: CheckCircle,
  user: User,
  logout: LogOut,
  info: Info,
  xCircle: XCircle,
} as const
